// AUTH.JS
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";



export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const START_FETCH_CATEGORIES = "START_FETCH_CATEGORIES";
export const START_FETCH_LEADS = "START_FETCH_LEADS";
export const START_FETCH_LEADS_AND_LIST = "START_FETCH_LEADS_AND_LIST";
export const FETCH_LEADS = "FETCH_LEADS";
export const START_FETCH_LISTS = "FETCH_LISTS";
export const START_FETCH_LEADNOTES = "START_FETCH_LEADNOTES";
export const FETCH_LISTS = "FETCH_LISTS";
export const FETCH_LEADNOTES = "FETCH_LEADNOTES";
export const ADD_LIST = "ADD_LIST";
export const START_DELETE_LIST = "START_DELETE_LIST";
export const START_DELETE_LEAD = "START_DELETE_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const DELETE_LISTLEAD = "DELETE_LISTLEAD";
export const FETCH_LIST_BY_ID = "FETCH_LIST_BY_ID";
export const ADD_LEAD_NOTE = "ADD_LEAD_NOTE";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const FETCH_LIST_WITH_LEADNOTES = "FETCH_LIST_WITH_LEADNOTES";
export const COMPLETE_FETCH_LEADS_AND_LIST = "COMPLETE_FETCH_LEADS_AND_LIST";
export const FETCH_ERROR = "FETCH_ERROR";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const DELETE_LIST_WITH_LEADNOTE = "DELETE_LIST_WITH_LEADNOTE";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const SORT_LISTS = "SORT_LISTS"
export const SORT_LEADLISTS = "SORT_LEADLISTS"
export const ADD_METRIC_LEADS = "ADD_METRIC_LEADS"